trigger:
  - master

resources:
  repositories:
    - repository: templates
      type: github
      name: Justin-DynamicD/azure_pipeline-templates
      endpoint: GitHub

jobs:
  - template: powershell_module.yml@templates
    parameters:
      module_name: adfs-management
      analyzer_profile: '.\\pipeline\\analyzer.profile'
